version: "3.9"

services:
  hadi-ameen-bot:
    image: ghcr.io/assergameel-soul/hadi-ameen-bot:latest
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      AZURE_DEVOPS_PAT: ${AZURE_DEVOPS_PAT}
